apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: services
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
---
kind: Namespace
apiVersion: v1
metadata:
  name: monitoring
---
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus
  namespace: monitoring
spec:
  interval: 5m
  timeout: 25m0s
  chart:
    spec:
      chart: kube-prometheus
      version: "8.15.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: services
      interval: 5m
  values:
    global:
      imageRegistry: harbor.services.mydomain.com/dh-proxy
    operator:
      service:
        type: ClusterIP 
    prometheus:
      prometheusExternalLabelName: run1
      ingress:
        enabled: true
        hostname: prom.run-01.mydomain.com
        ingressClassName: contour
      service:
        type: ClusterIP 
      externalLabels:
        cluster: run1
      thanos:
        create: true 
        service:
          type: ClusterIP
          annotations:
            projectcontour.io/upstream-protocol.h2c: "10901"
        ingress:
          enabled: true
          hostname: thanos.run-01.mydomain.com
          ingressClassName: contour